name: Build React on S3
on:
  push:
      branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main  # リポジトリをチェックアウト

      - name: Install Dependencies
        run: |
          cd src
          npm install

      - name: Translate secrets of base64 into json 
        env:
          JSON_DECODE: ${{ secrets.AWS_AMPLIFY_AUTH_CONFIG }}

        run: |
          echo $JSON_DECODE | base64 --decode > ./src/src/amp-config.json
          
      - name: Build
        run: |
          cd src
          npm run build

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd src
          aws s3 cp --recursive --region ap-northeast-1 build s3://full-empty-bucket
